### PR TITLE
BIDS FSL voxelwise p=0.001, voxelwise FWE p=0.05, clusterwise FWE p=0.05

### PR DESCRIPTION
**Pull request by AlexBowring**
This PR creates:
- FSL example voxelwise p=0.001 
- FSL example voxelwise FWE p=0.05
- FSL example cluster wise FWE p=0.05

All performed on ds011, sub-01, from [BIDS-compliant datasets](https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing).

### CODE REVIEW

**Comment by cmaumet** [comment]
Hi @AlexBowring! Your first commit "FSL voxelwise p=0.001 files" modifies files under `fsl_FWE_p005` (cf. 8c96675). Did you mean to upload another dataset? Could you write a short description listing which testing variants are added with in PR? 

Please hold on before pushing more data on this branch so that I can review those changes first.

**Comment by AlexBowring** [comment]
Hi @cmaumet. I have done some work on fsl_FWE_p005 and fsl_cluster_p005 so if those files have been modified it is probably just because I have deleted the old ones. I am planning on pushing the new fsl_FWE_p005 and fsl_cluster_p005 now (one at a time, so I don't break github). Is this okay?

**Comment by AlexBowring** [comment]
@cmaumet, I think I see what has happened. I did the pull request when I only had fsl_voxelwise_p0001 files on spm_fsl_ex, but then I pushed the fsl_FWE_p005 files onto spm_fsl_ex as well, so I'm guessing this becomes part of the pull request automatically as well?

**Comment by cmaumet** [comment]
Because this pull request (PR) is open, if you push more data it will automatically be added to the current PR. To create a separate pull request, you would have to create a new branch on your machine first.

**Comment by AlexBowring** [comment]
Okay makes sense! How about you decline this pull request... and I will just keep pushing to spm_fsl_ex and then do a big pull request at the end of the day when everything is done with everything described?

**Comment by cmaumet** [comment]
@AlexBowring: that's right ! But there is still an issue with you first commit titled "FSL voxelwise p=0.001 files", that do not modify files in "fsl_voxelwise_p0001". You can follow this link to view the files changed: 8c96675.

**Comment by AlexBowring** [comment]
@cmaumet It says it is not showing all the files because there are too many that have changed, Im guessing since fsl_FWE is first alphabetically it is only showing these files...? Since if you go on the spm_fsl_ex branch the fsl_voxelwise files have also been updated

**Comment by cmaumet** [comment]
Right, thanks for pointing this out!

**Comment by cmaumet** [comment]
I just had a look at the changes you made to p<0.001 voxel-wise (in the `spm_fsl_ex` branch)  and they look good! But, it looks like the `.nii.gz` files are not tracked using git lfs (but using git instead). This might be due to the fact that those data were pushed before we had git-lfs working properly... Anyway, to move those files to git-lfs, could you go back to `spm_fsl_ex` branch with:

```
git checkout spm_fsl_ex
```

and then:

```
cd fsl_voxelwise_p0001
git rm -r --cached .
git add .
git commit -m "Move files to git-lfs"
git push origin spm_fsl_ex
```

Also, I am not sure why the two files `report_stats.html` and `report_unwarp.html` are older (3 months old) than the other ones. Were we using the same data previously? If that's the case then it might be that they did not change, please let me know.

**Comment by AlexBowring** [comment]
Hi camille, in your last email was

git rm -r -cached

Ment to say

git rm -r -cached .

Alex

**Comment by cmaumet** [comment]
Thanks @AlexBowring (I have amended my comment above).

**Comment by AlexBowring** [comment]
@cmaumet I guess the reason the .html files are unchanged is because the content of those files has not changed, its just the files the are 'pointed' to within them that have. For example, in the stats.html it points to the 'Design.png' file, which will have been updated in the new upload, although this doesn't effect stats.html, does that make sense?

**Comment by cmaumet** [comment]
@AlexBowring: That makes sense. This looks good! Let's merge.

**Pull request merged**
