### PR TITLE
BIDS FSL gamma basis

### PR DESCRIPTION
**Pull request by AlexBowring**
This PR creates:
- FSL example gamma basis

Performed on  ds-011, sub-01, from [BIDS-compliant datasets](https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing).

### CODE REVIEW

**Comment by cmaumet** [comment]
Hi @AlexBowring. For this variant, it looks like the image files (.png) are not stored with git-lfs (e.g. [fsl_gamma_basis/design.png](https://github.com/incf-nidash/nidmresults-examples/blob/fsl_gamma_basis/fsl_gamma_basis/design.png)). Please run the following commands to make sure all files that should be tracked by git-lfs are:

```
git checkout fsl_gamma_basis
```

and then:

```
cd fsl_gamma_basis
git rm -r --cached .
git add .
git commit -m "Move files to git-lfs"
git push origin fsl_gamma_basis
```

Once you have done this update I think this will be good to go.

**Comment by AlexBowring** [comment]
Hi Camille,

Okay I have done that, this update should be good now

**Comment by cmaumet** [comment]
Okay! The git-lfs storage is sorted. 

One remaining issue is that it looks like both "tone counting vs baseline" and "tone counting probe vs baseline" contrasts are computed for this analysis. Is this FSL default behaviour when using Gamma basis functions? If not, could you update to have only one contrast (default)?

**Comment by AlexBowring** [comment]
Ah nuts, I think I did both the contrasts for all the FSL examples!

**Comment by cmaumet** [comment]
As discussed separatly by email, we will keep the 2-contrasts version for now, and update in the future if we re-process this data. https://github.com/incf-nidash/nidmresults-examples/issues/25 is open to keep track of this.

**Pull request merged**
