### PR TITLE
Upgrade to FSL 5.0.10

### PR DESCRIPTION
**Pull request by cmaumet**

### CODE REVIEW

**Comment by cmaumet** [comment]
(I've just rebased on master).

**Comment by TomMaullin** [comment]
Hi @cmaumet ,

I was just wondering is this branch okay to merge into master?

**Comment by cmaumet** [comment]
Yes, thanks!

**Comment by TomMaullin** [comment]
Ah... I've just realized I don't actually have merge permissions on this repository! Would it be okay if you gave me write access?

**Comment by cmaumet** [comment]
Sure! Done!

**Comment by TomMaullin** [comment]
Ah great! Thanks @cmaumet !

**Pull request merged**
