### PR TITLE
FSL OLS t test 

### PR DESCRIPTION
**Pull request by AlexBowring**
This PR creates:
- FSL OLS t test example complete
- FSL t test example README updated 

Performed on  all subjects of ds-011 from [BIDS-compliant datasets](https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing).

### CODE REVIEW

**Comment by cmaumet** [comment]
@AlexBowring: this PR cannot be automatically merged (see the `This branch has conflicts that must be resolved` message above). Could you investigate to see why this is happening? (We can have a look together this afternoon).

**Comment by AlexBowring** [comment]
@cmaumet Could it be because I made some changes to the README in the fsl_t_test directory? Otherwise I am not sure why.

**Comment by AlexBowring** [comment]
@cmaumet Okay this should be good to go now!

**Comment by cmaumet** [comment]
This is good to merge!

**Pull request merged**
