### PR TITLE
SPM WLS t test files

### PR DESCRIPTION
**Pull request by AlexBowring**
This PR creates:
- SPM WLS t test example with FWE p=0.05 threshold and excursion set image. 

Performed on  all subjects of ds-011 from [BIDS-compliant datasets](https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing).

### CODE REVIEW

**Comment by cmaumet** [comment]
@AlexBowring: did you meant WLS?

**Comment by AlexBowring** [comment]
@cmaumet Ach! Yes I did! Sorry I just did the FSL OLS example so had it stuck in my head!

**Comment by AlexBowring** [comment]
Maybe reject this because I gave the directory the OLS name, Ill change it.

**Comment by cmaumet** [comment]
Let's just update this PR. You can change the folder name, and then add/commit/push so that this PR is updated accordingly.

**Comment by AlexBowring** [comment]
@cmaumet Okay should be okay now!

**Comment by cmaumet** [comment]
Hi @AlexBowring, as discussed, this PR is currently using a corrected voxelwise FWE threshold but instead we would like a corrected _clusterwise_ threshold. To do that, you need to change the threshold (in `Results Report`) as follows:
- Threshold type: "none"
- Threshold: 0.001
- Extent (voxels): 2

The first two lines, specify the cluster-forming threshold to be p<0.001 uncorrected and in the last line, the "2" value corresponds to `FWEc` at the bottom of the SPM results page (cf. [SPM PDF](https://github.com/incf-nidash/nidmresults-examples/blob/spm_OLS_t_test/spm_WLS_t_test/mfx/spm_2016Apr11_001.pdf)).

Can you do this update and then I think this will be good to merge.

**Comment by cmaumet** [comment]
One more quick update to implement: [batch.m](https://github.com/incf-nidash/nidmresults-examples/blob/spm_OLS_t_test/spm_WLS_t_test/batch.m#L6) is referring to `spm_OLS_t_test` folder instead of `SPM_WLS_t_test`

**Comment by AlexBowring** [comment]
@cmaumet Hopefully this is good to go now

**Comment by cmaumet** [comment]
@AlexBowring: did you recompute the full analysis? I am wondering why the "beta" images have changed.

**Comment by AlexBowring** [comment]
@cmaumet Yes I did, it should all be correct though

**Comment by cmaumet** [comment]
Okay... I am going to merge but we might want to review this again later on.

**Pull request merged**
