### PR TITLE
BIDS SPM t test

### PR DESCRIPTION
**Pull request by AlexBowring**
This PR creates:
- SPM example 2nd level t-test

Performed on  all subjects of ds-011 from [BIDS-compliant datasets](https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing).

### CODE REVIEW

**Comment by cmaumet** [comment]
@AlexBowring: why not use the default analysis for the t-test example (i.e. fsl_voxelwise_p0001)?

**Comment by AlexBowring** [comment]
Hi Camille,

The t-test example is a 2nd level group t-test, whilst spm-voxelwise-p0001 is first level

**Comment by cmaumet** [comment]
I see! This PR corresponds to the "Data: Second level: 1 sample t-test no repeated measures" variant in our spreadsheet! I thought this was the "Test Type: 1 T-test (default)"... Could you make sure you mention the corresponding variant name when you create a new PR? I will review it now.

**Comment by cmaumet** [comment]
There is an issue with the .nii files: when opened on GitHub the text pointer is displayed instead of the file stored by git-lfs (see for e.g. https://github.com/incf-nidash/nidmresults-examples/blob/spm_t_test/spm_t_test/spmT_0001.nii). Could you check if the following commands help?

```
git checkout spm_t_test
```

and then:

```
cd spm_t_test
git rm -r --cached .
git add .
git commit -m "Move files to git-lfs"
git push origin spm_t_test
```

**Comment by AlexBowring** [comment]
For some reason this just isn't working, its allowing me to do 'git rm -r -cached .' but then when I try add the files nothing happens

**Comment by cmaumet** [comment]
So, the issue of the missing git-lfs files is now sorted (cf. https://github.com/github/git-lfs/issues/1056).

@AlexBowring: am I correct in assuming that this PR still needs to be updated to include the probe regressor at the subject-level?

**Comment by AlexBowring** [comment]
@cmaumet The probe regressor is a problem only for FSL examples, all SPM examples have this regressor included. The only thing with the SPM PR's currently open is the examples don't include the NIFTI image. However, this would be easier to do with these PR's merged, so I don't see any reason you should not merge this and the other open PR's!

**Comment by cmaumet** [comment]
Okay... By NIfTI image, you are referring to the thresholded image, right? Could you add it directly in here so that I have a complete analysis to review? Let me know if you need some guidance on how to include those changes in this branch.

**Comment by AlexBowring** [comment]
Yes, thats the image I mean. And sure, I will work on this branch (and for the other open PR's) for that (once buster git-lfs is updated) .

**Comment by cmaumet** [comment]
This PR was replaced by https://github.com/incf-nidash/nidmresults-examples/pull/56.

**Pull request closed without merging**
