### PR TITLE
SPM cluster k10 files

### PR DESCRIPTION
**Pull request by AlexBowring**
This PR creates:
- SPM cluster k10 example complete with excursion set image. 

Performed on  all subjects of ds-011 from [BIDS-compliant datasets](https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing).

### CODE REVIEW

**Comment by cmaumet** [comment]
@AlexBowring: the excursion set is missing (cf. [here](https://github.com/incf-nidash/nidmresults-examples/blob/spm_cluster_k10_complete/spm_cluster_k10/spmT_0001_thresh.nii)), can you push the object `1dc1dc2468336c169c9ef930c4253c852c84b3054470d5980def4bd8d679c233` using git-lfs push?

**Comment by AlexBowring** [comment]
Is that definitely the correct ID? Or, is the following the correct command… because at the moment I get :

git-lfs push --object-id 1dc1dc2468336c169c9ef930c4253c852c84b3054470d5980def4bd8d679c233
Invalid remote name “1dc1dc2468336c169c9ef930c4253c852c84b3054470d5980def4bd8d679c233"

**Comment by cmaumet** [comment]
Sorry the remote name (`origin`) was missing, the correct command is:

```
git-lfs push origin --object-id 1dc1dc2468336c169c9ef930c4253c852c84b3054470d5980def4bd8d679c233
```

FYI, you can check the object ID directly on the object page: https://github.com/incf-nidash/nidmresults-examples/blob/spm_cluster_k10_complete/spm_cluster_k10/spmT_0001_thresh.nii (just after `sha256:`)?

**Comment by AlexBowring** [comment]
Okay thanks, this looks to have worked!

**Comment by cmaumet** [comment]
This looks good!

**Pull request merged**
