### PR TITLE
SPM F test files updated

### PR DESCRIPTION
**Pull request by AlexBowring**
This PR creates:
- SPM F test contrasts updated so only the tone counting vs baseline contrast is exported. 

Performed on  all subjects of ds-011 from [BIDS-compliant datasets](https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing).

### CODE REVIEW

**Comment by cmaumet** [comment]
@AlexBowring: could you add the excursion set to this PR? It looks from the batch that it was not computed ("Write filtered images" is `None` instead of `Thresholded SPM`). You don't have to recompute the full analysis but just the last step ("Results Report"). Please update this branch (instead of creating a new one) so that I don't have to re-review it again. Thank you!

**Comment by AlexBowring** [comment]
@cmaumet This should be good now

**Comment by cmaumet** [comment]
Thanks @AlexBowring: could you upload the updated `batch.m` file as well?

**Comment by AlexBowring** [comment]
@cmaumet This should be included.

**Comment by cmaumet** [comment]
The batch still looks like the old one (i.e. filtered images not saved): https://github.com/incf-nidash/nidmresults-examples/blob/spm_f_test_update/spm_f_test/batch.m#L122 and https://github.com/incf-nidash/nidmresults-examples/pull/75/commits/0d47396f94a0e584b6a46e470d812bd9c5d6a835 does not modify `batch.m` as I would have expected. Do I miss something here?

**Comment by AlexBowring** [comment]
@cmaumet You are right, I will do this soon

**Comment by AlexBowring** [comment]
@cmaumet Okay, now it should be good!

**Comment by cmaumet** [comment]
This looks good to merge.

**Pull request merged**
