### PR TITLE
AFNI F-test, BLOCK HRF with 1 parameter, and TENT HRF

### PR DESCRIPTION
**Pull request by RuthPauli**
This PR creates:
- AFNI example F-test
- AFNI example with with BLOCK HRF with 1 parameter
- AFNI example with TENT HRF

All of those were performed on ds011 from [BIDS-compliant datasets](https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing).

### CODE REVIEW

**Comment by RuthPauli** [comment]
This set of commits (starting from f4410fc), implements the following updates:
- Stimulus duration corrected in all files that use BLOCK HRF basis.
- Only one contrast used in AFNI GAM and TENT  basis examples.

**Comment by cmaumet** [comment]
This PR is updating the following variants:
- AFNI example F-test => reviewed
- AFNI example with with BLOCK HRF with 1 parameter
- AFNI example with TENT HRF
- AFNI custom template
- AFNI cluster k>=10
- AFNI GAM HRF
- AFNI voxel-wise t>=4
- AFNI voxel-wise p<0.001 unc.
- AFNI voxel-wise p<0.05 FDR
- AFNI f-test
- AFNI cluster-wise FWE p<0.05
- AFNI cluster connectivity nn=2
- AFNI cluster connectivity nn=3

**Comment by cmaumet** [comment]
@RuthPauli: in the `afni_block_one_parameter` example, there are more than one script invoking `afni_proc.py` (e.g. [.orig.cmd.ap.sub_001](https://github.com/incf-nidash/nidmresults-examples/blob/afni_ex/afni_block_one_parameter/subject_results/group.DS000011/subj.sub_001/.orig.cmd.ap.sub_001), [cmd.ap.sub_001](https://github.com/incf-nidash/nidmresults-examples/blob/afni_ex/afni_block_one_parameter/subject_results/group.DS000011/subj.sub_001/cmd.ap.sub_001)), is this intended? If not, could you keep only the one script you used (and also check this is the case for the other examples)?

**Comment by cmaumet** [comment]
Hi @RuthPauli. Let's keep all the scripts (as discussed separately by email). Could you make sure that all the analyses uploaded in this PR are mentioned in the [variant spreadsheet](https://docs.google.com/spreadsheets/d/1uA5CfDTjUNKM5BwKc6QwdIvUiIGDGlGKksfWwZmEQ1Y/edit?usp=sharing). For example, we need a new line in the table for the `afni_block_one_parameter` variant.

**Comment by cmaumet** [comment]
Updated reviewed list:
- AFNI example with with BLOCK HRF with 1 parameter
- AFNI example with TENT HRF
- AFNI custom template
- AFNI cluster k>=10
- AFNI GAM HRF
- AFNI voxel-wise t>=4

@RuthPauli, so far I only have one small comment:
- Rethinking about the "AFNI custom template" variant, we should probably find a better name, e.g. "AFNI other template" variant (or something similar). "Custom template" is usually used to refer to a study-specific template which is not the case here. Could you rename the corresponding folder and update the spreadsheet?

**Comment by cmaumet** [comment]
Updated reviewed list:
- AFNI voxel-wise p<0.001 unc.
- AFNI cluster-wise FWE p<0.05
- AFNI cluster connectivity nn=2
- AFNI cluster connectivity nn=3

This is good to go!

**Pull request merged**
